Third exercise
LyudvaDmitry/Scala-complete-course pull request #2
Opened 2018-10-01 20:14 UTC by LyudvaDmitry

2018-10-02 07:10 UTC, aliksz commented on src/main/scala/lectures/functions/Authentication.scala
> +    case x => registeredCards.contains(x.credentials)
желательно не называть аргументы x, y, z 
когда есть какой то  конкретный контекст,
в данном случае пользователь

2018-10-02 11:09 UTC, snwlnx requested changes
Authentication надо поправить

2018-10-02 11:09 UTC, aliksz commented on src/main/scala/lectures/functions/Authentication.scala
> +    case x => registeredCards.contains(x.credentials)
в данном случае у тебя получилось не partial функция,
так как она определана на всех входных данных,
перепиши с типом [User, User]

2018-10-03 12:32 UTC, sergeypopov83 commented on src/main/scala/lectures/functions/Authentication.scala
> -    ???
то, что сделано безусловно имеет право на жизнь, но хотелось бы видеть код в таком виде
val fun = .. композиция функций authByLp и  authByCard
val authenticated: List[Option[User]] = for (user <- testUsers) yield {
fun(user)
}

2018-10-08 08:48 UTC, sergeypopov83 commented on src/main/scala/lectures/functions/Authentication.scala
> +    authByCard.orElse(authByLP).andThen(u => Some(u)).applyOrElse(user, (_: User) => None)
Я задание зачту, но есть 2 замечания! 
Во-первых authByCard.orElse(authByLP) надо делать снаружи цикла, т.к. иначе ты на каждого тестового пользователя создаешь новый объект функции
Во-вторых authByCard.orElse(authByLP).lift как развернет нужное значение.

т.е. твой код будет выглядеть как-то так
val f  =  authByCard.orElse(authByLP).lift 
val authenticated = for(users <- testUsers) 
    yield f(user)

2018-10-08 08:51 UTC, merged