Fourth exercise
LyudvaDmitry/Scala-complete-course pull request #3
Opened 2018-10-07 11:38 UTC by LyudvaDmitry

2018-10-07 11:41 UTC, LyudvaDmitry commented on src/main/scala/lectures/collections/OptionVsNPE.scala
> +      Option.apply(ConnectionProducer.produce(resource)).getOrElse(getConnection(resource))
Здесь вообще нужен Option? Кажется не очень осмысленным его создавать, чтобы сразу же распаковывать обратно. Не удобнее в таких случаях что-то такое делать?
```
      ConnectionProducer.produce(resource) match {
        case null => getConnection(resource)
        case connection => connection
      }
```

2018-10-07 19:22 UTC, snwlnx requested changes

2018-10-07 19:22 UTC, snwlnx commented on src/main/scala/lectures/collections/OptionVsNPE.scala
> +      Option.apply(ConnectionProducer.produce(resource)).getOrElse(getConnection(resource))
```.apply``` писать не обязательно (```Option(ResourceProducer.produce)```) 

Так выглядит вполне читаемо:

```
 Option(ConnectionProducer.produce(resource))
     .getOrElse(getConnection(resource))
```
насчет твоего варината, 
то это выглядит немного странно
 ```case connection => connection```
говорит что скорее всего можно без паттерн матчинга обойтись,
ну и ```case null ``` так на скале не пишут, идеологически что ли

2018-10-07 19:22 UTC, snwlnx commented on src/main/scala/lectures/collections/MergeSortImpl.scala
> +  println(mergeSort(Nil))
println(mergeSort(Vector(2, 1)))
что будет?

2018-10-07 19:22 UTC, snwlnx commented on src/main/scala/lectures/collections/MergeSortImpl.scala
> +      case (h1 :: t1, h2 :: t2) => if (h1 > h2) merge(list1, t2, acc :+ h2) else merge(t1, list2, acc :+ h1)
x:: xs , y:: ys, z::zs
как то так привычнее

2018-10-07 19:22 UTC, snwlnx commented on src/main/scala/lectures/collections/MergeSortImpl.scala
> +      case List(_) => data
паттерн для листа с одним элементом выглядит немного странно

2018-10-07 19:22 UTC, snwlnx commented on src/main/scala/lectures/collections/MergeSortImpl.scala
> +      case list => merge(mergeSort(list.take(list.length / 2)), mergeSort(list.drop(list.length / 2)), Nil)
в этой строке очень много всего,
желательно ее сделать более читаемой

2018-10-07 19:22 UTC, snwlnx commented on src/main/scala/lectures/collections/MergeSortImpl.scala
> +  private def merge(list1: Seq[Int], list2: Seq[Int], acc: Seq[Int]): Seq[Int] = {
acc здесь не нужен, 
можно без него переписать,
и лучше не называть индентификаторы с постфиксом 1 2 3 .. 
здесь лучше назвать left right например, так сразу больше смысла появляется

2018-10-10 16:31 UTC, LyudvaDmitry commented on src/main/scala/lectures/collections/MergeSortImpl.scala
> +  println(mergeSort(Nil))
List(1, 2)

2018-10-13 06:39 UTC, LyudvaDmitry commented on src/main/scala/lectures/collections/MergeSortImpl.scala
> +  println(mergeSort(Nil))
Переполнение стека, потому что я все написал с расчетом только на List :/

2018-10-13 06:53 UTC, LyudvaDmitry commented on src/main/scala/lectures/collections/MergeSortImpl.scala
> +  private def merge(list1: Seq[Int], list2: Seq[Int], acc: Seq[Int]): Seq[Int] = {
Я переписал без аккумулятора, но у меня получилась не хвостовая рекурсия. И есть ощущение, что хвостовая без аккумулятора и не получится.
Тут принципиально использовать хвостовую рекурсию, или так ок?
Кстати, есть какие-то способы понять, возможно ли в принципе применить для задачи хвостовую рекурсию?

2018-10-14 19:24 UTC, snwlnx approved these changes
ок, можно смержить

2018-10-14 19:24 UTC, snwlnx commented on src/main/scala/lectures/collections/MergeSortImpl.scala
> +      case seq if seq.size > 1 =>
case Seq(x)

2018-10-17 16:13 UTC, LyudvaDmitry commented on src/main/scala/lectures/collections/MergeSortImpl.scala
> +      case seq if seq.size > 1 =>
Это вроде будет сиквенс ровно с одним элементом, нет?

2018-10-17 16:13 UTC, merged

2018-10-21 17:29 UTC, aliksz commented on src/main/scala/lectures/collections/MergeSortImpl.scala
> +      case seq if seq.size > 1 =>
да, не то написал,
``` case Seq(x, xs@_*) ```